web:
   image: dockerregistry.ecosmob.net:5000/web_chat:v11
   restart: always
   #net: "host"
   container_name: php-apache
   ports:
        - "80:80"
        - "443:443"
   volumes:
        - ./ssl.conf:/etc/httpd/conf.d/ssl.conf
        - ./apache-selfsigned.key:/etc/ssl/private/apache-selfsigned.key
        - ./apache-selfsigned.crt:/etc/ssl/certs/apache-selfsigned.crt
        - ./non-ssl.conf:/etc/httpd/conf.d/non-ssl.conf
